// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package os

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/os/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func IsDarwin() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	v := starlarkfn.IsDarwin(execInterface)
	return v
}

func IsArchLinux() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	v := starlarkfn.IsArchLinux(fs)
	return v
}
