// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEnableServiceHandler is an autogenerated mock type for the EnableServiceHandler type
type MockEnableServiceHandler struct {
	mock.Mock
}

type EnableServiceHandlerEnableServiceArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	Name           string
	NameAnything   bool
}

type EnableServiceHandlerEnableServiceReturns struct {
	Err error
}

type EnableServiceHandlerEnableServiceExpectation struct {
	Args    EnableServiceHandlerEnableServiceArgs
	Returns EnableServiceHandlerEnableServiceReturns
}

func (_m *MockEnableServiceHandler) ApplyEnableServiceExpectation(e EnableServiceHandlerEnableServiceExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.NameAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Name)
	}
	_m.On("EnableService", args...).Return(e.Returns.Err)
}

func (_m *MockEnableServiceHandler) ApplyEnableServiceExpectations(expectations []EnableServiceHandlerEnableServiceExpectation) {
	for _, e := range expectations {
		_m.ApplyEnableServiceExpectation(e)
	}
}

// EnableService provides a mock function with given fields: ctx, dryrun, name
func (_m *MockEnableServiceHandler) EnableService(ctx context.Context, dryrun bool, name string) error {
	ret := _m.Called(ctx, dryrun, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) error); ok {
		r0 = rf(ctx, dryrun, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
