// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package systemd

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/systemd/handlers"
	"github.com/raba-jp/primus/pkg/operations/systemd/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func EnableService() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	enableServiceHandler := handlers.NewEnableService(execInterface)
	v := starlarkfn.EnableService(enableServiceHandler)
	return v
}

func StartService() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	startServiceHandler := handlers.NewStartService(execInterface)
	v := starlarkfn.StartService(startServiceHandler)
	return v
}
