// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandHandler is an autogenerated mock type for the CommandHandler type
type MockCommandHandler struct {
	mock.Mock
}

type CommandHandlerCommandArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *CommandParams
	PAnything      bool
}

type CommandHandlerCommandReturns struct {
	Err error
}

type CommandHandlerCommandExpectation struct {
	Args    CommandHandlerCommandArgs
	Returns CommandHandlerCommandReturns
}

func (_m *MockCommandHandler) ApplyCommandExpectation(e CommandHandlerCommandExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Command", args...).Return(e.Returns.Err)
}

func (_m *MockCommandHandler) ApplyCommandExpectations(expectations []CommandHandlerCommandExpectation) {
	for _, e := range expectations {
		_m.ApplyCommandExpectation(e)
	}
}

// Command provides a mock function with given fields: ctx, dryrun, p
func (_m *MockCommandHandler) Command(ctx context.Context, dryrun bool, p *CommandParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *CommandParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
