// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package packages

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/packages/handlers"
	"github.com/raba-jp/primus/pkg/operations/packages/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func Install() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	fs := backend.NewFs()
	checkInstallHandler := handlers.NewCheckInstall(execInterface, fs)
	installHandler := handlers.NewInstall(execInterface, fs)
	v := starlarkfn.Install(checkInstallHandler, installHandler)
	return v
}
