run:
  tests: false
  skip-dirs:
    - exec
linters:
  disable:
    - funlen
    - dupl
    - gofumpt
    - nlreturn
    - wsl
    - lll
    - gochecknoglobals
    - godot
    - gochecknoinits
  disable-all: false
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  fast: false
