// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package command

import (
	"github.com/raba-jp/primus/pkg/modules"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func NewFunctions() starlark.Value {
	execInterface := modules.NewExecInterface()
	executeRunner := Execute(execInterface)
	executableRunner := Executable(execInterface)
	value := newFunctions(executeRunner, executableRunner)
	return value
}

// wire.go:

func newFunctions(execute ExecuteRunner, executable ExecutableRunner) starlark.Value {
	dict := starlark.NewDict(2)
	dict.SetKey(starlark.String("execute"), starlark.NewBuiltin("execute", NewExecuteFunction(execute)))
	dict.SetKey(starlark.String("executable"), starlark.NewBuiltin("executable", NewExecutableFunction(executable)))
	return dict
}
