// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package command

import (
	"github.com/raba-jp/primus/pkg/backend"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func NewFunctions() starlark.Value {
	execute := backend.NewExecute()
	executable := backend.NewExecutable()
	value := newFunctions(execute, executable)
	return value
}

// wire.go:

func newFunctions(execute backend.Execute, executable backend.Executable) starlark.Value {
	dict := starlark.NewDict(2)
	dict.SetKey(starlark.String("execute"), starlark.NewBuiltin("execute", NewExecuteFunction(execute)))
	dict.SetKey(starlark.String("executable"), starlark.NewBuiltin("executable", NewExecutableFunction(executable)))
	return dict
}
