// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package command

import (
	"github.com/raba-jp/primus/pkg/modules"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func NewFunctions() starlark.Value {
	execInterface := modules.NewExecInterface()
	executeRunner := Execute(execInterface)
	fs := modules.NewFs()
	osDetector := modules.NewOSDetector(execInterface, fs)
	value := newFunctions(executeRunner, osDetector)
	return value
}

// wire.go:

func newFunctions(exc ExecuteRunner, detector modules.OSDetector) starlark.Value {
	dict := starlark.NewDict(2)
	dict.SetKey(starlark.String("execute"), starlark.NewBuiltin("execute", NewExecuteFunction(exc)))
	dict.SetKey(starlark.String("executable"), starlark.NewBuiltin("executable", NewExecutableFunction(detector)))
	return dict
}
