// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package darwin

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/darwin/handlers"
	"github.com/raba-jp/primus/pkg/operations/darwin/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func CheckInstall() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	fs := backend.NewFs()
	checkInstallHandler := handlers.NewCheckInstall(execInterface, fs)
	v := starlarkfn.CheckInstall(checkInstallHandler)
	return v
}

func Install() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	fs := backend.NewFs()
	checkInstallHandler := handlers.NewCheckInstall(execInterface, fs)
	installHandler := handlers.NewInstall(checkInstallHandler, execInterface)
	v := starlarkfn.Install(installHandler)
	return v
}

func Uninstall() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	fs := backend.NewFs()
	checkInstallHandler := handlers.NewCheckInstall(execInterface, fs)
	uninstallHandler := handlers.NewUninstall(checkInstallHandler, execInterface)
	v := starlarkfn.Uninstall(uninstallHandler)
	return v
}
