// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package git

import (
	"github.com/raba-jp/primus/pkg/operations/git/handlers"
	"github.com/raba-jp/primus/pkg/operations/git/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func Clone() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	storerInitializer := handlers.SetFileSystemStore()
	cloneHandler := handlers.NewClone(storerInitializer)
	v := starlarkfn.Clone(cloneHandler)
	return v
}
