// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EnableServiceHandler is an autogenerated mock type for the EnableServiceHandler type
type EnableServiceHandler struct {
	mock.Mock
}

type EnableServiceHandlerRunArgs struct {
	Ctx          context.Context
	CtxAnything  bool
	Name         string
	NameAnything bool
}

type EnableServiceHandlerRunReturns struct {
	Err error
}

type EnableServiceHandlerRunExpectation struct {
	Args    EnableServiceHandlerRunArgs
	Returns EnableServiceHandlerRunReturns
}

func (_m *EnableServiceHandler) ApplyRunExpectation(e EnableServiceHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.NameAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Name)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *EnableServiceHandler) ApplyRunExpectations(expectations []EnableServiceHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, name
func (_m *EnableServiceHandler) Run(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
