// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StartServiceHandler is an autogenerated mock type for the StartServiceHandler type
type StartServiceHandler struct {
	mock.Mock
}

type StartServiceHandlerStartServiceArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	Name           string
	NameAnything   bool
}

type StartServiceHandlerStartServiceReturns struct {
	Err error
}

type StartServiceHandlerStartServiceExpectation struct {
	Args    StartServiceHandlerStartServiceArgs
	Returns StartServiceHandlerStartServiceReturns
}

func (_m *StartServiceHandler) ApplyStartServiceExpectation(e StartServiceHandlerStartServiceExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.NameAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Name)
	}
	_m.On("StartService", args...).Return(e.Returns.Err)
}

func (_m *StartServiceHandler) ApplyStartServiceExpectations(expectations []StartServiceHandlerStartServiceExpectation) {
	for _, e := range expectations {
		_m.ApplyStartServiceExpectation(e)
	}
}

// StartService provides a mock function with given fields: ctx, dryrun, name
func (_m *StartServiceHandler) StartService(ctx context.Context, dryrun bool, name string) error {
	ret := _m.Called(ctx, dryrun, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) error); ok {
		r0 = rf(ctx, dryrun, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
