// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/network/handlers"
	mock "github.com/stretchr/testify/mock"
)

// HTTPRequestHandler is an autogenerated mock type for the HTTPRequestHandler type
type HTTPRequestHandler struct {
	mock.Mock
}

type HTTPRequestHandlerRunArgs struct {
	Ctx         context.Context
	CtxAnything bool
	P           *handlers.HTTPRequestParams
	PAnything   bool
}

type HTTPRequestHandlerRunReturns struct {
	Err error
}

type HTTPRequestHandlerRunExpectation struct {
	Args    HTTPRequestHandlerRunArgs
	Returns HTTPRequestHandlerRunReturns
}

func (_m *HTTPRequestHandler) ApplyRunExpectation(e HTTPRequestHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *HTTPRequestHandler) ApplyRunExpectations(expectations []HTTPRequestHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, p
func (_m *HTTPRequestHandler) Run(ctx context.Context, p *handlers.HTTPRequestParams) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *handlers.HTTPRequestParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
