// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package file

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/file/handlers"
	"github.com/raba-jp/primus/pkg/operations/file/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func Copy() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	copyHandler := handlers.NewCopy(fs)
	v := starlarkfn.Copy(copyHandler)
	return v
}

func Move() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	moveHandler := handlers.NewMove(fs)
	v := starlarkfn.Move(moveHandler)
	return v
}

func Symlink() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	symlinkHandler := handlers.NewSymlink(fs)
	v := starlarkfn.Symlink(symlinkHandler)
	return v
}
