// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package vscode

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/vscode/handlers"
	"github.com/raba-jp/primus/pkg/operations/vscode/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func InstallExtension() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	installExtensionHandler := handlers.NewInstallExtension(execInterface)
	v := starlarkfn.InstallExtension(installExtensionHandler)
	return v
}
