// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/directory/handlers"
	mock "github.com/stretchr/testify/mock"
)

// CreateHandler is an autogenerated mock type for the CreateHandler type
type CreateHandler struct {
	mock.Mock
}

type CreateHandlerCreateArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *handlers.CreateParams
	PAnything      bool
}

type CreateHandlerCreateReturns struct {
	Err error
}

type CreateHandlerCreateExpectation struct {
	Args    CreateHandlerCreateArgs
	Returns CreateHandlerCreateReturns
}

func (_m *CreateHandler) ApplyCreateExpectation(e CreateHandlerCreateExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Create", args...).Return(e.Returns.Err)
}

func (_m *CreateHandler) ApplyCreateExpectations(expectations []CreateHandlerCreateExpectation) {
	for _, e := range expectations {
		_m.ApplyCreateExpectation(e)
	}
}

// Create provides a mock function with given fields: ctx, dryrun, p
func (_m *CreateHandler) Create(ctx context.Context, dryrun bool, p *handlers.CreateParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *handlers.CreateParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
