// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/directory/handlers"
	mock "github.com/stretchr/testify/mock"
)

// CreateHandler is an autogenerated mock type for the CreateHandler type
type CreateHandler struct {
	mock.Mock
}

type CreateHandlerRunArgs struct {
	Ctx         context.Context
	CtxAnything bool
	P           *handlers.CreateParams
	PAnything   bool
}

type CreateHandlerRunReturns struct {
	Err error
}

type CreateHandlerRunExpectation struct {
	Args    CreateHandlerRunArgs
	Returns CreateHandlerRunReturns
}

func (_m *CreateHandler) ApplyRunExpectation(e CreateHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *CreateHandler) ApplyRunExpectations(expectations []CreateHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, p
func (_m *CreateHandler) Run(ctx context.Context, p *handlers.CreateParams) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *handlers.CreateParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
