// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDarwinPkgInstallHandler is an autogenerated mock type for the DarwinPkgInstallHandler type
type MockDarwinPkgInstallHandler struct {
	mock.Mock
}

type DarwinPkgInstallHandlerInstallArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *DarwinPkgInstallParams
	PAnything      bool
}

type DarwinPkgInstallHandlerInstallReturns struct {
	Err error
}

type DarwinPkgInstallHandlerInstallExpectation struct {
	Args    DarwinPkgInstallHandlerInstallArgs
	Returns DarwinPkgInstallHandlerInstallReturns
}

func (_m *MockDarwinPkgInstallHandler) ApplyInstallExpectation(e DarwinPkgInstallHandlerInstallExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Install", args...).Return(e.Returns.Err)
}

func (_m *MockDarwinPkgInstallHandler) ApplyInstallExpectations(expectations []DarwinPkgInstallHandlerInstallExpectation) {
	for _, e := range expectations {
		_m.ApplyInstallExpectation(e)
	}
}

// Install provides a mock function with given fields: ctx, dryrun, p
func (_m *MockDarwinPkgInstallHandler) Install(ctx context.Context, dryrun bool, p *DarwinPkgInstallParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *DarwinPkgInstallParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
