// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArchPkgInstallHandler is an autogenerated mock type for the ArchPkgInstallHandler type
type MockArchPkgInstallHandler struct {
	mock.Mock
}

type ArchPkgInstallHandlerInstallArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *ArchPkgInstallParams
	PAnything      bool
}

type ArchPkgInstallHandlerInstallReturns struct {
	Err error
}

type ArchPkgInstallHandlerInstallExpectation struct {
	Args    ArchPkgInstallHandlerInstallArgs
	Returns ArchPkgInstallHandlerInstallReturns
}

func (_m *MockArchPkgInstallHandler) ApplyInstallExpectation(e ArchPkgInstallHandlerInstallExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Install", args...).Return(e.Returns.Err)
}

func (_m *MockArchPkgInstallHandler) ApplyInstallExpectations(expectations []ArchPkgInstallHandlerInstallExpectation) {
	for _, e := range expectations {
		_m.ApplyInstallExpectation(e)
	}
}

// Install provides a mock function with given fields: ctx, dryrun, p
func (_m *MockArchPkgInstallHandler) Install(ctx context.Context, dryrun bool, p *ArchPkgInstallParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *ArchPkgInstallParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
