// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package network

import (
	"github.com/raba-jp/primus/pkg/functions/command"
	"github.com/raba-jp/primus/pkg/modules"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func NewFunctions() starlark.Value {
	execInterface := modules.NewExecInterface()
	executeRunner := command.Execute(execInterface)
	gitCloneRunner := GitClone(executeRunner)
	client := modules.NewHTTPClient()
	fs := modules.NewFs()
	httpRequestRunner := HTTPRequest(client, fs)
	value := newFunctions(gitCloneRunner, httpRequestRunner)
	return value
}

// wire.go:

func newFunctions(clone GitCloneRunner, httpRequest HTTPRequestRunner) starlark.Value {
	dict := starlark.NewDict(2)
	dict.SetKey(starlark.String("git_clone"), starlark.NewBuiltin("git_clone", NewGitCloneFunction(clone)))
	dict.SetKey(starlark.String("http_request"), starlark.NewBuiltin("http_request", NewHTTPRequestFunction(httpRequest)))
	return dict
}
