// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package directory

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/directory/handlers"
	"github.com/raba-jp/primus/pkg/operations/directory/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func Create() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	createHandler := handlers.New(fs)
	v := starlarkfn.Create(createHandler)
	return v
}
