// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSetVariableHandler is an autogenerated mock type for the SetVariableHandler type
type MockSetVariableHandler struct {
	mock.Mock
}

type SetVariableHandlerSetVariableArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *SetVariableParams
	PAnything      bool
}

type SetVariableHandlerSetVariableReturns struct {
	Err error
}

type SetVariableHandlerSetVariableExpectation struct {
	Args    SetVariableHandlerSetVariableArgs
	Returns SetVariableHandlerSetVariableReturns
}

func (_m *MockSetVariableHandler) ApplySetVariableExpectation(e SetVariableHandlerSetVariableExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("SetVariable", args...).Return(e.Returns.Err)
}

func (_m *MockSetVariableHandler) ApplySetVariableExpectations(expectations []SetVariableHandlerSetVariableExpectation) {
	for _, e := range expectations {
		_m.ApplySetVariableExpectation(e)
	}
}

// SetVariable provides a mock function with given fields: ctx, dryrun, p
func (_m *MockSetVariableHandler) SetVariable(ctx context.Context, dryrun bool, p *SetVariableParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *SetVariableParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
