// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package network

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/network/handlers"
	"github.com/raba-jp/primus/pkg/operations/network/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func HTTPRequest() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	client := backend.NewHTTPClient()
	fs := backend.NewFs()
	httpRequestHandler := handlers.NewHTTPRequest(client, fs)
	v := starlarkfn.HTTPRequest(httpRequestHandler)
	return v
}
