// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSymlinkHandler is an autogenerated mock type for the SymlinkHandler type
type MockSymlinkHandler struct {
	mock.Mock
}

type SymlinkHandlerSymlinkArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *SymlinkParams
	PAnything      bool
}

type SymlinkHandlerSymlinkReturns struct {
	Err error
}

type SymlinkHandlerSymlinkExpectation struct {
	Args    SymlinkHandlerSymlinkArgs
	Returns SymlinkHandlerSymlinkReturns
}

func (_m *MockSymlinkHandler) ApplySymlinkExpectation(e SymlinkHandlerSymlinkExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Symlink", args...).Return(e.Returns.Err)
}

func (_m *MockSymlinkHandler) ApplySymlinkExpectations(expectations []SymlinkHandlerSymlinkExpectation) {
	for _, e := range expectations {
		_m.ApplySymlinkExpectation(e)
	}
}

// Symlink provides a mock function with given fields: ctx, dryrun, p
func (_m *MockSymlinkHandler) Symlink(ctx context.Context, dryrun bool, p *SymlinkParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *SymlinkParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
