// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package repl

import (
	"github.com/raba-jp/primus/pkg/starlark/builtin"
)

// Injectors from wire.go:

func Initialize() PromptFunc {
	state := NewState()
	thread := newThread()
	stringDict := builtin.NewBuiltinFunction()
	replREPL := NewREPL(state, thread, stringDict)
	executor := NewExecutor(replREPL)
	completer := NewCompleter()
	promptFunc := NewPrompt(replREPL, executor, completer)
	return promptFunc
}
