// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPRequestHandler is an autogenerated mock type for the HTTPRequestHandler type
type MockHTTPRequestHandler struct {
	mock.Mock
}

type HTTPRequestHandlerHTTPRequestArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *HTTPRequestParams
	PAnything      bool
}

type HTTPRequestHandlerHTTPRequestReturns struct {
	Err error
}

type HTTPRequestHandlerHTTPRequestExpectation struct {
	Args    HTTPRequestHandlerHTTPRequestArgs
	Returns HTTPRequestHandlerHTTPRequestReturns
}

func (_m *MockHTTPRequestHandler) ApplyHTTPRequestExpectation(e HTTPRequestHandlerHTTPRequestExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("HTTPRequest", args...).Return(e.Returns.Err)
}

func (_m *MockHTTPRequestHandler) ApplyHTTPRequestExpectations(expectations []HTTPRequestHandlerHTTPRequestExpectation) {
	for _, e := range expectations {
		_m.ApplyHTTPRequestExpectation(e)
	}
}

// HTTPRequest provides a mock function with given fields: ctx, dryrun, p
func (_m *MockHTTPRequestHandler) HTTPRequest(ctx context.Context, dryrun bool, p *HTTPRequestParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *HTTPRequestParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
