// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/fish/handlers"
	mock "github.com/stretchr/testify/mock"
)

// SetPathHandler is an autogenerated mock type for the SetPathHandler type
type SetPathHandler struct {
	mock.Mock
}

type SetPathHandlerRunArgs struct {
	Ctx         context.Context
	CtxAnything bool
	P           *handlers.SetPathParams
	PAnything   bool
}

type SetPathHandlerRunReturns struct {
	Err error
}

type SetPathHandlerRunExpectation struct {
	Args    SetPathHandlerRunArgs
	Returns SetPathHandlerRunReturns
}

func (_m *SetPathHandler) ApplyRunExpectation(e SetPathHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *SetPathHandler) ApplyRunExpectations(expectations []SetPathHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, p
func (_m *SetPathHandler) Run(ctx context.Context, p *handlers.SetPathParams) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *handlers.SetPathParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
