// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/fish/handlers"
	mock "github.com/stretchr/testify/mock"
)

// SetVariableHandler is an autogenerated mock type for the SetVariableHandler type
type SetVariableHandler struct {
	mock.Mock
}

type SetVariableHandlerRunArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *handlers.SetVariableParams
	PAnything      bool
}

type SetVariableHandlerRunReturns struct {
	Err error
}

type SetVariableHandlerRunExpectation struct {
	Args    SetVariableHandlerRunArgs
	Returns SetVariableHandlerRunReturns
}

func (_m *SetVariableHandler) ApplyRunExpectation(e SetVariableHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *SetVariableHandler) ApplyRunExpectations(expectations []SetVariableHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, dryrun, p
func (_m *SetVariableHandler) Run(ctx context.Context, dryrun bool, p *handlers.SetVariableParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *handlers.SetVariableParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
