// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/fish/handlers"
	mock "github.com/stretchr/testify/mock"
)

// SetPathHandler is an autogenerated mock type for the SetPathHandler type
type SetPathHandler struct {
	mock.Mock
}

type SetPathHandlerSetPathArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *handlers.SetPathParams
	PAnything      bool
}

type SetPathHandlerSetPathReturns struct {
	Err error
}

type SetPathHandlerSetPathExpectation struct {
	Args    SetPathHandlerSetPathArgs
	Returns SetPathHandlerSetPathReturns
}

func (_m *SetPathHandler) ApplySetPathExpectation(e SetPathHandlerSetPathExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("SetPath", args...).Return(e.Returns.Err)
}

func (_m *SetPathHandler) ApplySetPathExpectations(expectations []SetPathHandlerSetPathExpectation) {
	for _, e := range expectations {
		_m.ApplySetPathExpectation(e)
	}
}

// SetPath provides a mock function with given fields: ctx, dryrun, p
func (_m *SetPathHandler) SetPath(ctx context.Context, dryrun bool, p *handlers.SetPathParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *handlers.SetPathParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
