// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExecutableHandler is an autogenerated mock type for the ExecutableHandler type
type ExecutableHandler struct {
	mock.Mock
}

type ExecutableHandlerExecutableArgs struct {
	Ctx          context.Context
	CtxAnything  bool
	Name         string
	NameAnything bool
}

type ExecutableHandlerExecutableReturns struct {
	Ok bool
}

type ExecutableHandlerExecutableExpectation struct {
	Args    ExecutableHandlerExecutableArgs
	Returns ExecutableHandlerExecutableReturns
}

func (_m *ExecutableHandler) ApplyExecutableExpectation(e ExecutableHandlerExecutableExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.NameAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Name)
	}
	_m.On("Executable", args...).Return(e.Returns.Ok)
}

func (_m *ExecutableHandler) ApplyExecutableExpectations(expectations []ExecutableHandlerExecutableExpectation) {
	for _, e := range expectations {
		_m.ApplyExecutableExpectation(e)
	}
}

// Executable provides a mock function with given fields: ctx, name
func (_m *ExecutableHandler) Executable(ctx context.Context, name string) bool {
	ret := _m.Called(ctx, name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
