// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package arch

import (
	"github.com/raba-jp/primus/pkg/backend"
	"github.com/raba-jp/primus/pkg/operations/arch/handlers"
	"github.com/raba-jp/primus/pkg/operations/arch/starlarkfn"
	handlers2 "github.com/raba-jp/primus/pkg/operations/command/handlers"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func CheckInstall() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	checkInstallHandler := handlers.NewCheckInstall(execInterface)
	v := starlarkfn.CheckInstall(checkInstallHandler)
	return v
}

func Install() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	checkInstallHandler := handlers.NewCheckInstall(execInterface)
	fs := backend.NewFs()
	executableHandler := handlers2.NewExecutable(fs)
	installHandler := handlers.NewInstall(checkInstallHandler, executableHandler, execInterface)
	v := starlarkfn.Install(installHandler)
	return v
}

func Uninstall() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	execInterface := backend.NewExecInterface()
	checkInstallHandler := handlers.NewCheckInstall(execInterface)
	uninstallHandler := handlers.NewUninstall(checkInstallHandler, execInterface)
	v := starlarkfn.Uninstall(uninstallHandler)
	return v
}

func MultipleInstall() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	fs := backend.NewFs()
	executableHandler := handlers2.NewExecutable(fs)
	execInterface := backend.NewExecInterface()
	multipleInstallHandler := handlers.NewMultipleInstall(executableHandler, execInterface)
	v := starlarkfn.MultipleInstall(multipleInstallHandler)
	return v
}
