// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package fish

import (
	"github.com/raba-jp/primus/pkg/functions/command"
	"github.com/raba-jp/primus/pkg/modules"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func NewFunctions() starlark.Value {
	execInterface := modules.NewExecInterface()
	executeRunner := command.Execute(execInterface)
	setVariableRunner := SetVariable(executeRunner)
	setPathRunner := SetPath(executeRunner)
	value := newFunctions(setVariableRunner, setPathRunner)
	return value
}

// wire.go:

func newFunctions(
	setVariable SetVariableRunner,
	setPath SetPathRunner,
) starlark.Value {
	dict := starlark.NewDict(2)
	dict.SetKey(starlark.String("set_variable"), starlark.NewBuiltin("set_variable", NewSetVariableFunction(setVariable)))
	dict.SetKey(starlark.String("set_path"), starlark.NewBuiltin("set_path", NewSetPathFunction(setPath)))
	return dict
}
