// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/arch/handlers"
	mock "github.com/stretchr/testify/mock"
)

// MultipleInstallHandler is an autogenerated mock type for the MultipleInstallHandler type
type MultipleInstallHandler struct {
	mock.Mock
}

type MultipleInstallHandlerRunArgs struct {
	Ctx         context.Context
	CtxAnything bool
	P           *handlers.MultipleInstallParams
	PAnything   bool
}

type MultipleInstallHandlerRunReturns struct {
	Err error
}

type MultipleInstallHandlerRunExpectation struct {
	Args    MultipleInstallHandlerRunArgs
	Returns MultipleInstallHandlerRunReturns
}

func (_m *MultipleInstallHandler) ApplyRunExpectation(e MultipleInstallHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *MultipleInstallHandler) ApplyRunExpectations(expectations []MultipleInstallHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, p
func (_m *MultipleInstallHandler) Run(ctx context.Context, p *handlers.MultipleInstallParams) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *handlers.MultipleInstallParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
