// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func Initialize() *cobra.Command {
	applyCommand := NewApplyCommand()
	versionCommand := NewVersionCommand()
	replCommand := NewReplCommand()
	command := NewCommand(applyCommand, versionCommand, replCommand)
	return command
}
