// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/file/handlers"
	mock "github.com/stretchr/testify/mock"
)

// CopyHandler is an autogenerated mock type for the CopyHandler type
type CopyHandler struct {
	mock.Mock
}

type CopyHandlerRunArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *handlers.CopyParams
	PAnything      bool
}

type CopyHandlerRunReturns struct {
	Err error
}

type CopyHandlerRunExpectation struct {
	Args    CopyHandlerRunArgs
	Returns CopyHandlerRunReturns
}

func (_m *CopyHandler) ApplyRunExpectation(e CopyHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *CopyHandler) ApplyRunExpectations(expectations []CopyHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, dryrun, p
func (_m *CopyHandler) Run(ctx context.Context, dryrun bool, p *handlers.CopyParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *handlers.CopyParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
