// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	handlers "github.com/raba-jp/primus/pkg/operations/file/handlers"
	mock "github.com/stretchr/testify/mock"
)

// MoveHandler is an autogenerated mock type for the MoveHandler type
type MoveHandler struct {
	mock.Mock
}

type MoveHandlerRunArgs struct {
	Ctx            context.Context
	CtxAnything    bool
	Dryrun         bool
	DryrunAnything bool
	P              *handlers.MoveParams
	PAnything      bool
}

type MoveHandlerRunReturns struct {
	Err error
}

type MoveHandlerRunExpectation struct {
	Args    MoveHandlerRunArgs
	Returns MoveHandlerRunReturns
}

func (_m *MoveHandler) ApplyRunExpectation(e MoveHandlerRunExpectation) {
	var args []interface{}
	if e.Args.CtxAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Ctx)
	}
	if e.Args.DryrunAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Dryrun)
	}
	if e.Args.PAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.P)
	}
	_m.On("Run", args...).Return(e.Returns.Err)
}

func (_m *MoveHandler) ApplyRunExpectations(expectations []MoveHandlerRunExpectation) {
	for _, e := range expectations {
		_m.ApplyRunExpectation(e)
	}
}

// Run provides a mock function with given fields: ctx, dryrun, p
func (_m *MoveHandler) Run(ctx context.Context, dryrun bool, p *handlers.MoveParams) error {
	ret := _m.Called(ctx, dryrun, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, *handlers.MoveParams) error); ok {
		r0 = rf(ctx, dryrun, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
