name: lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          only-new-issues: true
