// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package special

import (
	"io"
	"os"

	"github.com/raba-jp/primus/pkg/operations/special/starlarkfn"
	"go.starlark.net/starlark"
)

// Injectors from wire.go:

func RequirePrevilegedAccess() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	ioReader := reader()
	v := starlarkfn.RequirePrevilegedAccess(ioReader)
	return v
}

func PrintContext() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kargs []starlark.Tuple) (starlark.Value, error) {
	v := starlarkfn.PrintContext()
	return v
}

// wire.go:

func reader() io.Reader {
	return os.Stdin
}
